apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: backend-app
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-app
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080